### ISSUE TITLE
A little help...

### ISSUE THREAD

**Issue by xino1010** [offchan42/superkeras#1]
Dear @off99555 
I am interested in applying the permutational layer to my model that consists of:
30 individual features for element A, 30 individual features for elment B and 9 common characteristics.

I would like to train my model using **permutational_layer.py**

Could you guide me using you project?

Regards

**Comment by off99555** [comment]
For now, you can download the `kerashelper.py` and `permutational_layer.py` into your folder and import `permutational_layer` to use it.
If you want it without much details, use `PermutationalModule`. But if you want more fine-tuned options, use the individual functions inside that file and compose them.
The example is in the file itself.
To know how to use it, I suggest you run `python permutational_layer.py`, and look at the bottom section of the code. Compare the result line by line from the code to the output, try to make sense of it and you should learn better how to use the module.

**Comment by off99555** [comment]
You should see that I use the function `repeat_layers` a lot. It's the function I wrote myself.
It's simply creating a list of same layers. E.g. when you want 2 dense layers with 16 neurons and 4 neurons respectively, you would write:
`repeat_layers(Dense, [16, 4], activation="relu")`

You can also write `[Dense(16, activation='relu'), Dense(4, activation='relu')]` for a more verbose way.
